spring :
  data:
    mongodb:
      uri : mongodb://127.0.0.1:27017/
      database : urlMapping
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000
discord_webhook: https://discordapp.com/api/webhooks/1192008652773658694/XkwEECrTHZjhj6uBQh_mOKmNeYg58BhB-6q25uJhadA27j8eJbG_tlm3qPfKfPrfNvhX
ratelimiter:
  instances:
    public:
      limitForPeriod: 2
      limitRefreshPeriod: 1m
      timeoutDuration: 1s
